stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: apcenter/dcr
      pushRemote: true
      registry: index.docker.io
timeout: 60
